### ISSUE TITLE
FFI, ioctl/termios - request of help

### ISSUE THREAD

**Issue by adjivas** [JanWielemaker/ffi#7]
Hello! Thank you for this project

I try to use it for call a ioctl(2) function.
The prototype of this function is `int ioctl(int fd, unsigned long request, struct termios *term);`
What I need is to declare a termios struct variable, and to call the `ioctl` function with a pointer on this variable.

So I have defined library and my prototype of functions like this: 
```prolog
#!/usr/bin/swipl

:- use_module(library(ffi)).
:- use_module(library(cerror)).

:- c_import("#include <sys/ioctl.h>
             #include <termios.h>",
            [ 'libc' ], [
                ioctl(int, ulong, -struct(termios), [int])
            ]).
```
I imagined declare a termios struct like this but `c_alloc(Ptr, -struct(termios))` returned false.
```prolog
:- initialization(main, main).

main(_Argv) :-
    c_alloc(Ptr, -struct(termios)), % ==> false
    ioctl(0, 21509, Ptr, _), nl.
```
Do can you help me with that?

**Comment by JanWielemaker** [comment]
Please use the Discourse forum for questions.

The 3rd arg of ioctl() is `...`.   That causes it not to pull in the termios struct.    If we use

```
:- c_import("#include <sys/ioctl.h>
             #include <termios.h>
             #include <unistd.h>",
            [ 'libc' ], [
                tcgetattr(+int, -struct(termios), [-int])
            ]).
```

We can do things like this.   Note that there is no `-` for the c_alloc/2 call and if it is an output struct (declared using -struct(Name)), the interface allocates the struct for us.

```
39 ?- c_alloc(Ptr, struct(termios)).
Ptr = <C struct termios[1]>(0x55850bb7a700).

40 ?- tcgetattr(0, P, R).
P = <C struct termios[1]>(0x55850bb356c0),
R = 0.
```

For ioctl you need to lookup the section on variadic functions.   Note that the types you declare are the Prolog facing types.   The library gets the C types from the headers and validates that it can make the conversion.
